# Generated by Django 5.2.4 on 2025-10-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_vendor_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_signatory",
            field=models.BooleanField(default=False),
        ),
    ]
