# Generated by Django 5.2.4 on 2026-01-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_oldvendor_organization_organizationtype_recipient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldVendor',
        ),
    ]
