# Generated by Django 5.2.4 on 2025-09-08 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0011_agreement_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="parent_agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_agreements",
                to="agreements.agreement",
                verbose_name="Parent Agreement",
            ),
        ),
    ]
