# Generated by Django 5.2.4 on 2025-09-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0012_agreement_parent_agreement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="status",
            field=models.CharField(
                choices=[("Ongoing", "Ongoing"), ("Expired", "Expired")],
                default="Ongoing",
                max_length=15,
            ),
        ),
    ]
