# Generated by Django 5.2.4 on 2026-01-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0013_update_status_capitalization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='party_name',
        ),
        migrations.AddField(
            model_name='agreement',
            name='party_name_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
