# Generated by Django 5.2.4 on 2025-11-29 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_designation_remove_user_is_signatory_and_more'),
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='signatory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_letters', to='accounts.signatory'),
        ),
    ]
