# Generated by Django 5.2.4 on 2025-12-08 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_add_signatory_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='letter_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='letters.letter')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
