# Generated by Django 5.2.4 on 2025-12-13 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_letterfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencecounter',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_counters', to='letters.organization'),
        ),
        migrations.AlterField(
            model_name='referencecounter',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
