# Generated by Django 5.2.4 on 2025-12-14 00:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_alter_referencecounter_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
