# Generated by Django 5.2.4 on 2026-01-13 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_oldvendor_organization_organizationtype_recipient_and_more'),
        ('letters', '0005_alter_letter_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_letters', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='referencecounter',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_counters', to='accounts.organization'),
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='organization',
        ),
        migrations.AlterField(
            model_name='letter',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_letters', to='accounts.recipient'),
        ),
        migrations.AlterField(
            model_name='lettercopyrecipient',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.recipient'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
    ]
